### ISSUE TITLE
Compatibility of packages with netcdf file formats

### ISSUE THREAD

**Issue by estherelle** [M6ASP/getting-started#1]
- Which packages can work with which version of netCDF?
- Can packages work with data in non-file format?
  - OpenDAP
  - files inside other containers (e.g. tar file)

Tasks:
- Compile a new notebook with all of the different packages that checks if it can open/read the files (loop over modules and files)
- Summarize compatibility of packages

**Comment by adcroft** [comment]
Making this issue a milestone.
