### ISSUE TITLE
Tutorial for a beginner making a basic plot using netCDF4

### ISSUE THREAD

**Issue by adcroft** [M6ASP/getting-started#11]
- Read data
- Plot the data
- Annotate (using meta inform from #10)

**Comment by estherelle** [comment]
https://github.com/M6ASP/getting-started/blob/master/Reading%20data%20with%20netCDF4.ipynb

Meta-data in separate notebook here: https://github.com/M6ASP/getting-started/blob/master/Reading%20metadata%20with%20netcdf4.ipynb
