### ISSUE TITLE
Query meta-data using scipy.io.netcdf

### ISSUE THREAD

**Issue by adcroft** [M6ASP/getting-started#8]
Open the example data, figure out what is in there and what it means.

**Comment by adcroft** [comment]
Currently this is part of the notebook for #9. It could stay that way or be handled separately?

**Comment by estherelle** [comment]
If we were to separate the metadata, should that be specific to scipy.io.netcdf or the other modules as well? I was thinking of having a notebook that compares the modules and how they query metadata- I know we mentioned having a notebook that documented the different modules, but I don't remember if we wanted to do that for the metadata. Or, is this meant to be focused on explaining what the metadata is?

**Comment by adcroft** [comment]
I think we need explanation about examining and using meta-data using each package because (unfortunately) not everyone will have access to the right package. This is mostly what makes up each of the notebooks as they currently stand. If we were to separate the parts, would there be enough left to describe plotting on it's own?

I think a comparison between packages should be more holistic and about all aspects (meta-data, ease-of-use, plotting, etc.) so that it can be the basis of a recommendation.

**Comment by estherelle** [comment]
https://github.com/M6ASP/getting-started/blob/master/Reading%20metadata%20with%20scipy.io.netcdf.ipynb
